name: reminders
description: Read, Edit, Create and Delete Apple Reminders
version: 1.0.1
homepage: https://github.com/berkobob/reminders

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: RemindersPlugin
      macos:
        pluginClass: RemindersPlugin
